kind: Deployment
apiVersion: apps/v1
metadata: 
    name: dougas-web
spec:
    selector:
        matchLabels:
            app: react
    replicas: 2
    template:
        metadata:
            labels:
                app: react
        spec:
            containers:
            - name: douglaskamalreactapp
              image: vd84/douglaskamaldockerreactimage:latest
              ports:
              - containerPort: 3001